# Config and textures by cm|sheik

[[textures]]

author = "inexor"
name = "sky"
version = "v1"

[[textures]]

author = "sheik"
name = "cream"
version = "v1"

[[textures]]

author = "sheik"
name = "cyan"
version = "v1"

[[textures]]

author = "sheik"
name = "black"
version = "v1"

[[textures]]

author = "sheik"
name = "pink"
version = "v1"

[[textures]]

author = "sheik"
name = "white"
version = "v1"

[[textures]]

author = "sheik"
name = "cream"
version = "v1"

[[textures]]

author = "sheik"
name = "caution"
version = "v1"

